version: "3.9"

services:
  prometheus-init:
    image: alpine:3.18
    container_name: prometheus-init
    env_file:
      - .env.prometheus
    volumes:
      - ./prometheus.yml.template:/templates/prometheus.yml.template:ro
      - prometheus_config:/etc/prometheus
    entrypoint:
      - /bin/sh
      - -c
      - |
        apk add --no-cache gettext
        echo "Generando configuración de Prometheus..."
        envsubst < /templates/prometheus.yml.template > /etc/prometheus/prometheus.yml
        echo "✅ Configuración generada con éxito."

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_config:/etc/prometheus:ro
    depends_on:
      prometheus-init:
        condition: service_completed_successfully
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle

volumes:
  prometheus_config:
    driver: local
